version: "3.9"

# Variables for mysql database
x-mysql-database: &MYSQL_DATABASE devdb
x-mysql-user: &MYSQL_USER devuser
x-mysql-password: &MYSQL_PASSWORD devdev

services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/workspace/Dockerfile
    container_name: go-lambda-sample-workspace
    tty: true
    volumes:
      - .:/go/src/github.com/mkaiho/go-lambda-sample
    working_dir: /go/src/github.com/mkaiho/go-lambda-sample
    ports:
      - 3000:3000
  mysqldb:
    build:
      context: ./docker/mysql
      dockerfile: ./Dockerfile
    container_name: go-lambda-sample-db
    ports:
      - 13306:3306
    volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: *MYSQL_DATABASE
      MYSQL_USER: *MYSQL_USER
      MYSQL_PASSWORD: *MYSQL_PASSWORD
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "127.0.0.1:53:53"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:443:443"
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "./docker/localstack:/tmp/localstack"
